package com.ifr.anomaly.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.Serializable;
import java.util.Map;

/**
 * Represents an external alert event arriving from the industrial-alerts Kafka topic.
 *
 * These are generated by the fake-data-generator (or real monitoring systems like
 * Prometheus AlertManager / Zabbix) and carry discrete alert records rather than
 * continuous metric streams.
 *
 * When cross-referenced with metric-based anomaly detection, they provide:
 *   - Faster confirmation (skip de-jitter when both agree)
 *   - Higher confidence in the root cause
 *   - Additional context for the Supervisor's diagnosis
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class AlertEvent implements Serializable {

    private static final long serialVersionUID = 1L;

    @JsonProperty("alert_id")
    private String alertId;

    @JsonProperty("timestamp")
    private long timestamp;          // epoch milliseconds

    @JsonProperty("node_id")
    private String nodeId;

    @JsonProperty("node_type")
    private String nodeType;

    @JsonProperty("metric_type")
    private String metricType;

    @JsonProperty("current_value")
    private double currentValue;

    @JsonProperty("severity")
    private String severity;

    @JsonProperty("anomaly_scenario")
    private String anomalyScenario;

    @JsonProperty("tags")
    private Map<String, String> tags;

    // ---- Derived / pipeline fields ----

    /** Set to true when this alert has been matched with a metric anomaly. */
    private boolean matched;

    // ---- Getters / Setters ----

    public String getAlertId() { return alertId; }
    public void setAlertId(String alertId) { this.alertId = alertId; }

    public long getTimestamp() { return timestamp; }
    public void setTimestamp(long timestamp) { this.timestamp = timestamp; }

    public String getNodeId() { return nodeId; }
    public void setNodeId(String nodeId) { this.nodeId = nodeId; }

    public String getNodeType() { return nodeType; }
    public void setNodeType(String nodeType) { this.nodeType = nodeType; }

    public String getMetricType() { return metricType; }
    public void setMetricType(String metricType) { this.metricType = metricType; }

    public double getCurrentValue() { return currentValue; }
    public void setCurrentValue(double currentValue) { this.currentValue = currentValue; }

    public String getSeverity() { return severity; }
    public void setSeverity(String severity) { this.severity = severity; }

    public String getAnomalyScenario() { return anomalyScenario; }
    public void setAnomalyScenario(String anomalyScenario) { this.anomalyScenario = anomalyScenario; }

    public Map<String, String> getTags() { return tags; }
    public void setTags(Map<String, String> tags) { this.tags = tags; }

    public boolean isMatched() { return matched; }
    public void setMatched(boolean matched) { this.matched = matched; }
}
